version: '3'

services:
  db:
    image: postgres:14-alpine
    hostname: nestpg
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    networks:
      - pg-admin

  # test-db:
  #   image: postgres:14-alpine
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_PASSWORD: pass123

networks:
  pg-admin:
    external: true
